[package]
name = "jedfgames/rbx-package-loader"
description = "A toolchain for managing Roblox instance-based packages deterministically."
version = "0.0.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/jedfgames/rbx-package-loader"
include = [
    "default.project.json",
    "init.luau",
    "LICENSE",
    "README.md",
    "Source",
    "Source/**",
    "wally.toml",
]
exclude = ["**"]

[dependencies]
t = "horsenuggets/t@3.1.1-horse.0.3"

[dev-dependencies]
Dotenv = "horsenuggets/dotenv-luau@0.1.2"
Testable = "horsenuggets/testable@0.1.0"
